### ISSUE TITLE
Fig S7 reproduction

### ISSUE THREAD

**Issue by billnjcn111** [livnatje/ImmuneResistance#2]
Hi,
which code was used to calculate TCGA sample resistance w or w/o non-malignant cell filtered in FigS7
thx

**Comment by livnatje** [comment]
Hi,

The code is provided in ImmRes4_predictICBresponses.R (functions: set.TCGA, and then prd.TCGA.survival).

See https://github.com/livnatje/ImmuneResistance/wiki/Predicting-immunotherapy-resistance (item 4).

Livnat
