### ISSUE TITLE
Is more comprehensive gene expression data available?

### ISSUE THREAD

**Issue by benstaf** [livnatje/ImmuneResistance#3]
Hello Livnat,

I am interested to use the bulk-RNA-seq data from validation cohort 2 that I found here:

[https://portals.broadinstitute.org/single_cell/study/SCP109/melanoma-immunotherapy-resistance#study-download](url)

However, some gene expression data is missing, especially the gene expression status of CXCL10, IFNG, CXCL9, IDO1, HLA-DRA, STAT1 . Is it available somewhere else?

Mostapha

**Comment by livnatje** [comment]
@mostafachatillon, we provided only the validation data we used for our analyses. The full validation cohort will be published soon as a part of a separated effort. I will provide the link here once it's published.
