### ISSUE TITLE
Where are your predictions of the clinical response?

### ISSUE THREAD

**Issue by benstaf** [livnatje/ImmuneResistance#4]
Hello Livnat,

How to access your predictions of the clinical response to immunotherapy for the previous studies: Hugo et al. 2016, Riaz et al. 2017, Van Allen et al. 2015?

(your tutorial suggests to look at "ImmRes4_predictICBresponses.R", but there are a lot of rds files and abbreviations inside, and I am a bit confused)

**Comment by benstaf** [comment]
I unsuccessfully tried to look at the file 'public.ICB.datasets.rds', and for Van Allen et al.:
`patients ID: results$"aCTLA4"$samples`
`scores: results$"aCTLA4"$res$resF`
but it's not right, because I found AUC=0.54, but your paper announces 0.79

**Comment by livnatje** [comment]
@mostafachatillon, here is a quote from the paper: "In 42 melanoma patients treated with
CTLA-4 blockade using ipilimumab (Van Allen et al., 2015), it was lower in the two complete-responders pre-treatment."
