### ISSUE TITLE
Applying the approach to other datasets, with only bulk RNA-seq data

### ISSUE THREAD

**Issue by benstaf** [livnatje/ImmuneResistance#5]
Hello,

I would like to apply your approach to other datasets, as suggested here:
https://github.com/livnatje/ImmuneResistance/wiki/Applying-the-approach-to-other-datasets

In particular, I want to predict ICI results for melanoma. Can I use this approach with only bulk-RNA data from each patient?

If yes, I only have bulk.tpm: where to find the other inputs?

Can you give a concrete example of application to other datasets?

I am especially interested in plugging bulk RNA seq data from Riaz et al.

**Comment by livnatje** [comment]
Hi @mostafachatillon, sorry for the late response. You can definitely use the cell.cell.interactions.new.dataset code with other bulk-RNA data. You will also need scRNA-Seq data from the same cancer type, so you can use our melanoma single-cell cohort.

Note its probably better to use large bulk cohorts, as the (TCGA) one we used.
